CREATE DATABASE bdPartidoPTC

USE bdPartidoPTC

SELECT * FROM filiados_PTC

--Ex1
SELECT NOME_DO_FILIADO FROM filiados_PTC
WHERE NOME_DO_FILIADO LIKE 'ANTONIO%'

--EX2
SELECT NOME_DO_FILIADO FROM filiados_PTC
WHERE NOME_DO_FILIADO LIKE '%SEBASTIAO%'

SELECT NOME_DO_FILIADO FROM filiados_PTC
WHERE NOME_DO_FILIADO LIKE '%SEBASTIAO'

--EX3
SELECT NOME_DO_FILIADO FROM filiados_PTC
WHERE NOME_DO_FILIADO LIKE 'OS%'

--EX4
SELECT NOME_DO_MUNICIPIO, NOME_DO_FILIADO FROM filiados_PTC
WHERE NOME_DO_MUNICIPIO LIKE 'SÃO FÉLIX'

--EX5
SELECT NOME_DO_MUNICIPIO, NOME_DO_FILIADO FROM filiados_PTC
WHERE NOME_DO_MUNICIPIO LIKE 'INHAMBUPE'

--EX6
SELECT NOME_DO_MUNICIPIO, NOME_DO_FILIADO FROM filiados_PTC
WHERE NOME_DO_MUNICIPIO LIKE 'SANTA%'

--EX7
SELECT NOME_DO_MUNICIPIO, NOME_DO_FILIADO FROM filiados_PTC
WHERE NOME_DO_MUNICIPIO LIKE 'E%'

--EX8
SELECT NOME_DO_MUNICIPIO, NOME_DO_FILIADO FROM filiados_PTC
WHERE NOME_DO_MUNICIPIO LIKE '%CRUZ%'

--EX9
SELECT NOME_DO_MUNICIPIO, NOME_DO_FILIADO FROM filiados_PTC
WHERE NOME_DO_MUNICIPIO LIKE '%DE%'

--EX10
SELECT NOME_DO_FILIADO, DATA_DA_FILIACAO FROM filiados_PTC
WHERE DATA_DA_FILIACAO BETWEEN '01/01/1990' AND '01/01/2000'

--EX11
SELECT NOME_DO_FILIADO, DATA_DA_FILIACAO FROM filiados_PTC
WHERE DATA_DA_FILIACAO BETWEEN '02/01/2010' AND '01/03/2010'

--EX12
SELECT NOME_DO_FILIADO,  DATA_DA_FILIACAO FROM filiados_PTC
WHERE DATA_DA_FILIACAO BETWEEN '01/07/2007' AND '01/01/2008'

--EX13
SELECT NOME_DO_FILIADO, SITUACAO_DO_REGISTRO FROM filiados_PTC
WHERE SITUACAO_DO_REGISTRO LIKE 'REGULAR'

--EX14
SELECT NOME_DO_FILIADO, ZONA_ELEITORAL FROM filiados_PTC
WHERE ZONA_ELEITORAL LIKE '203'

--EX15
SELECT NOME_DO_FILIADO, ZONA_ELEITORAL FROM filiados_PTC
WHERE ZONA_ELEITORAL LIKE '180'

--EX16
SELECT NOME_DO_FILIADO, ZONA_ELEITORAL FROM filiados_PTC
WHERE ZONA_ELEITORAL LIKE '199'

--EX17
SELECT ZONA_ELEITORAL FROM filiadosPTC
ORDER BY ZONA_ELEITORAL ASC

--EX18
//NÃO FAZER!!!

--EX19
UPDATE filiados_PTC
SET SIGLA_DO_PARTIDO='PT'
WHERE CODIGO_DO_MUNICIPIO = 36471;

SELECT SIGLA_DO_PARTIDO, CODIGO_DO_MUNICIPIO FROM filiados_PTC
WHERE CODIGO_DO_MUNICIPIO = 36471

--EX20
UPDATE filiados_PTC
SET SIGLA_DO_PARTIDO='PMDB'
WHERE CODIGO_DO_MUNICIPIO = 38490;

SELECT SIGLA_DO_PARTIDO, CODIGO_DO_MUNICIPIO FROM filiados_PTC
WHERE CODIGO_DO_MUNICIPIO = 38490

--EX21
UPDATE filiados_PTC
SET SIGLA_DO_PARTIDO='PC'
WHERE NOME_DO_MUNICIPIO = 'SANTANÓPOLIS';

SELECT SIGLA_DO_PARTIDO, NOME_DO_MUNICIPIO FROM filiados_PTC
WHERE NOME_DO_MUNICIPIO = 'SANTANÓPOLIS'

--EX22
UPDATE filiados_PTC
SET SIGLA_DO_PARTIDO='PV' , NOME_DO_PARTIDO='Partido Verde dos Filiados'
WHERE NOME_DO_MUNICIPIO = 'SÃO FÉLIX';
SELECT SIGLA_DO_PARTIDO, NOME_DO_MUNICIPIO, NOME_DO_PARTIDO FROM filiados_PTC
WHERE NOME_DO_MUNICIPIO = 'SÃO FÉLIX'

--EX23
UPDATE filiadosPTC
SET SIGLA_DO_PARTIDO='PSDB' , NOME_DO_PARTIDO=' Partido da Social Democracia Brasileira '
WHERE NOME_DO_MUNICIPIO = 'ENCRUZILHADA';
SELECT SIGLA_DO_PARTIDO,NOME_DO_MUNICIPIO, NOME_DO_PARTIDO FROM filiadosPTC
WHERE NOME_DO_MUNICIPIO = 'ENCRUZILHADA'

--EX24
UPDATE filiadosPTC
SET NOME_DO_FILIADO='JORGE LUIS MAGALHÃES DOS SANTOS'
WHERE NOME_DO_FILIADO = 'JORGE LUIS FERREIRA DOS SANTOS'
SELECT NOME_DO_FILIADO FROM filiadosPTC
WHERE NOME_DO_FILIADO = 'JORGE LUIS MAGALHÃES DOS SANTOS'

--EX25
UPDATE filiadosPTC
SET NOME_DO_FILIADO='RENATA XAVIER RODRIGUES'
WHERE NOME_DO_FILIADO = 'BENTA XAVIER RODRIGUES'

--EX26
UPDATE filiadosPTC
SET NOME_DO_FILIADO='NOEL LEITE DA SILVA'
WHERE NOME_DO_FILIADO = 'NOE LEITE DA SILVA'

--EX27
UPDATE filiadosPTC
SET SITUACAO_DO_REGISTRO='REGULAR'
WHERE NOME_DO_FILIADO = 'NOE LEITE DA SILVA'
SELECT NOME_DO_FILIADO FROM filiadosPTC
WHERE SITUACAO_DO_REGISTRO = ''

--EX28
UPDATE filiadosPTC
SET SITUACAO_DO_REGISTRO='REGULAR'
WHERE NOME_DO_FILIADO = 'ELIEL ALMEIDA SILVA'
SELECT NOME_DO_FILIADO FROM filiadosPTC
WHERE SITUACAO_DO_REGISTRO = 'DESFILIADO'

--EX29
UPDATE filiadosPTC
SET SITUACAO_DO_REGISTRO='DESFILIADO'
WHERE NOME_DO_FILIADO = 'ALINE DE SOUZA'
SELECT NOME_DO_FILIADO FROM filiadosPTC
WHERE SITUACAO_DO_REGISTRO = 'REGULAR'